"""Initial schema: survey_sessions, survey_responses, optouts

Revision ID: 218dc9a12304
Revises: 
Create Date: 2025-12-07 15:19:07.328892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '218dc9a12304'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optouts',
    sa.Column('phone_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of phone number for privacy'),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When the user opted out'),
    sa.Column('opt_out_message', sa.String(length=200), nullable=True, comment='The opt-out message sent by user (e.g., STOP)'),
    sa.PrimaryKeyConstraint('phone_hash')
    )
    op.create_table('survey_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of phone number for privacy'),
    sa.Column('survey_id', sa.String(length=100), nullable=False, comment='Survey identifier from YAML filename'),
    sa.Column('survey_version', sa.String(length=100), nullable=False, comment='Git commit SHA when survey was loaded'),
    sa.Column('current_step', sa.String(length=100), nullable=False, comment='Current step ID in survey flow'),
    sa.Column('consent_given', sa.Boolean(), nullable=False, comment='Whether user has consented to data collection'),
    sa.Column('consent_requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When consent was first requested'),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True, comment='When user gave consent'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When survey session started'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Last update timestamp'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When survey was completed (NULL for active sessions)'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of validation retries for current step'),
    sa.Column('context', sa.JSON(), server_default=sa.text("('{}')"), nullable=False, comment='JSONB storage for survey variables (name, zip, etc.)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_completed_at', 'survey_sessions', ['completed_at'], unique=False)
    op.create_index('idx_phone_hash_survey', 'survey_sessions', ['phone_hash', 'survey_id'], unique=False)
    op.create_index('idx_updated_at', 'survey_sessions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_survey_sessions_phone_hash'), 'survey_sessions', ['phone_hash'], unique=False)
    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Foreign key to survey_sessions table'),
    sa.Column('step_id', sa.String(length=100), nullable=False, comment='ID of the survey step being answered'),
    sa.Column('response_text', sa.Text(), nullable=False, comment='Raw text response from user'),
    sa.Column('stored_value', sa.Text(), nullable=True, comment='Processed/validated value stored in context'),
    sa.Column('responded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When the response was submitted'),
    sa.Column('is_valid', sa.Boolean(), nullable=False, comment='Whether the response passed validation'),
    sa.ForeignKeyConstraint(['session_id'], ['survey_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_step', 'survey_responses', ['session_id', 'step_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_session_id'), 'survey_responses', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_responses_session_id'), table_name='survey_responses')
    op.drop_index('idx_session_step', table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_survey_sessions_phone_hash'), table_name='survey_sessions')
    op.drop_index('idx_updated_at', table_name='survey_sessions')
    op.drop_index('idx_phone_hash_survey', table_name='survey_sessions')
    op.drop_index('idx_completed_at', table_name='survey_sessions')
    op.drop_table('survey_sessions')
    op.drop_table('optouts')
    # ### end Alembic commands ###
